version: "3.8"

services:
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./common:/common
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./common:/common
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  keycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - server

volumes:
  mongodb-data: ./mongodb-data
  postgres-data: ./postgres-data
